language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
sudo: required

services:
  - mysql
 
services:
  - mysql
  
matrix:
    include:
        - os: linux
          dist: trusty          

before_install:
  - uname -a
  - php --version
  - mysqladmin -uroot status
  - composer self-update
  - sudo chmod 777 -R symfony/cache
  - sudo chmod 777 -R symfony/log

install:
  - composer install -d symfony/lib
  - bash installer/cli_install.sh

script:
  - symfony/lib/vendor/bin/codecept run -c symfony/test/api/

notifications:
  email: true
